import '../../features/birthday/models/quote.dart';

class Quotes {
  static final List<Quote> all = [
    // --- Romantic Birthday Quotes (50) ---
    Quote(text: "Happy Birthday, my love. Every heartbeat of mine wishes you joy.", category: QuoteCategory.romantic),
    Quote(text: "You make my world brighter every single day. Cheers to your birthday!", category: QuoteCategory.romantic),
    Quote(text: "Happy Birthday to the one who makes ordinary days extraordinary.", category: QuoteCategory.romantic),
    Quote(text: "On your birthday, I just want to remind you: you are my forever.", category: QuoteCategory.romantic),
    Quote(text: "Another year older, another year more in love with you.", category: QuoteCategory.romantic),
    Quote(text: "Your smile is the best gift I get every day. Happy Birthday, darling.", category: QuoteCategory.romantic),
    Quote(text: "With you, every moment feels like a celebration. Especially today!", category: QuoteCategory.romantic),
    Quote(text: "Happy Birthday, sweetheart. You are my wish come true.", category: QuoteCategory.romantic),
    Quote(text: "Each candle on your cake is a wish I make for your happiness.", category: QuoteCategory.romantic),
    Quote(text: "The world is lucky to have you, but I’m the luckiest of all.", category: QuoteCategory.romantic),
    Quote(text: "Another birthday means another chance to love you even more.", category: QuoteCategory.romantic),
    Quote(text: "No gift can match the gift you are in my life. Happy Birthday.", category: QuoteCategory.romantic),
    Quote(text: "May today be as sweet as your kiss and as warm as your hug.", category: QuoteCategory.romantic),
    Quote(text: "I’m grateful the stars aligned to bring me you. Happy Birthday.", category: QuoteCategory.romantic),
    Quote(text: "You make time stop and hearts race. Happy Birthday, love.", category: QuoteCategory.romantic),
    Quote(text: "Being with you makes every year the best one yet.", category: QuoteCategory.romantic),
    Quote(text: "Happy Birthday to my soulmate, my partner, my best friend.", category: QuoteCategory.romantic),
    Quote(text: "Today is about you, but I celebrate you every day.", category: QuoteCategory.romantic),
    Quote(text: "With you by my side, life is one endless birthday party.", category: QuoteCategory.romantic),
    Quote(text: "Your love is my favorite gift, but today you deserve them all.", category: QuoteCategory.romantic),
    Quote(text: "Happy Birthday! I hope your day shines as brightly as your eyes.", category: QuoteCategory.romantic),
    Quote(text: "Every candle blown is another promise of love from me to you.", category: QuoteCategory.romantic),
    Quote(text: "Growing older with you feels like the greatest adventure ever.", category: QuoteCategory.romantic),
    Quote(text: "I fall for you more deeply with each passing birthday.", category: QuoteCategory.romantic),
    Quote(text: "Happy Birthday to the reason my heart beats faster every day.", category: QuoteCategory.romantic),
    Quote(text: "All I want is to grow old celebrating birthdays by your side.", category: QuoteCategory.romantic),
    Quote(text: "The best gift I can give is my love—forever yours.", category: QuoteCategory.romantic),
    Quote(text: "To me, you’re timeless. Happy Birthday, my forever love.", category: QuoteCategory.romantic),
    Quote(text: "You make my world feel new each year. Happy Birthday.", category: QuoteCategory.romantic),
    Quote(text: "If love were a candle, mine would burn forever for you.", category: QuoteCategory.romantic),
    Quote(text: "Happy Birthday! You are my today, tomorrow, and always.", category: QuoteCategory.romantic),
    Quote(text: "I’d blow out every candle in the world to wish for you again.", category: QuoteCategory.romantic),
    Quote(text: "Every birthday of yours is another reason to cherish you.", category: QuoteCategory.romantic),
    Quote(text: "Happy Birthday to the love who makes my life complete.", category: QuoteCategory.romantic),
    Quote(text: "You are my song, my dream, my everything. Happy Birthday.", category: QuoteCategory.romantic),
    Quote(text: "Your laughter is my favorite melody. Sing it loud today!", category: QuoteCategory.romantic),
    Quote(text: "Every year with you is my new favorite year.", category: QuoteCategory.romantic),
    Quote(text: "Happy Birthday to my sunshine on cloudy days.", category: QuoteCategory.romantic),
    Quote(text: "With you, love grows sweeter with every candle blown.", category: QuoteCategory.romantic),
    Quote(text: "Today is proof the universe wanted me to be this lucky.", category: QuoteCategory.romantic),
    Quote(text: "Happy Birthday! You’re my forever Valentine.", category: QuoteCategory.romantic),
    Quote(text: "The day you were born, the world became magical.", category: QuoteCategory.romantic),
    Quote(text: "Loving you is the easiest wish I’ll ever make.", category: QuoteCategory.romantic),
    Quote(text: "Happy Birthday! Let me wrap you in love today and always.", category: QuoteCategory.romantic),
    Quote(text: "Each year your beauty amazes me more. Happy Birthday!", category: QuoteCategory.romantic),
    Quote(text: "Happy Birthday to my better half, my heart, my world.", category: QuoteCategory.romantic),
    Quote(text: "The flame of my love will never blow out. Happy Birthday.", category: QuoteCategory.romantic),
    Quote(text: "With you, life feels like an endless honeymoon. Happy Birthday.", category: QuoteCategory.romantic),
    Quote(text: "You’re not aging—you’re becoming more lovable every year.", category: QuoteCategory.romantic),
    Quote(text: "Happy Birthday! Let’s turn this day into our forever memory.", category: QuoteCategory.romantic),

    // --- General Birthday Quotes (50) ---
    Quote(text: "Happy Birthday! May your cake be sweet and your laughter endless.", category: QuoteCategory.birthday),
    Quote(text: "Another year, another chapter. Write it beautifully.", category: QuoteCategory.birthday),
    Quote(text: "Celebrate today like it’s the best gift you’ve ever received.", category: QuoteCategory.birthday),
    Quote(text: "Birthdays are nature’s way of saying: keep smiling!", category: QuoteCategory.birthday),
    Quote(text: "May your special day overflow with happiness and surprises.", category: QuoteCategory.birthday),
    Quote(text: "Happy Birthday! May this year bring dreams closer to reality.", category: QuoteCategory.birthday),
    Quote(text: "A birthday is not the end of a year but the start of a new one.", category: QuoteCategory.birthday),
    Quote(text: "Count blessings, not candles. Happy Birthday!", category: QuoteCategory.birthday),
    Quote(text: "Wishing you joy as endless as the stars in the sky.", category: QuoteCategory.birthday),
    Quote(text: "Happy Birthday! May your journey ahead be full of light.", category: QuoteCategory.birthday),
    Quote(text: "Celebrate big, laugh loud, love more—today is yours!", category: QuoteCategory.birthday),
    Quote(text: "Happy Birthday! May you glow brighter than your candles.", category: QuoteCategory.birthday),
    Quote(text: "Age is just a number, but today is a treasure.", category: QuoteCategory.birthday),
    Quote(text: "Wishing you a year as colorful as confetti and balloons.", category: QuoteCategory.birthday),
    Quote(text: "Happy Birthday! You deserve every smile today brings.", category: QuoteCategory.birthday),
    Quote(text: "Here’s to another year of adventure and growth.", category: QuoteCategory.birthday),
    Quote(text: "Happy Birthday! May your heart stay forever young.", category: QuoteCategory.birthday),
    Quote(text: "Celebrate the amazing person you’ve become today.", category: QuoteCategory.birthday),
    Quote(text: "Happy Birthday! May your cake be sweet and your wishes sweeter.", category: QuoteCategory.birthday),
    Quote(text: "Birthdays are milestones—enjoy this stop on your journey.", category: QuoteCategory.birthday),
    Quote(text: "Happy Birthday! Let happiness wrap around you today.", category: QuoteCategory.birthday),
    Quote(text: "Wishing you sunshine, laughter, and endless cheer.", category: QuoteCategory.birthday),
    Quote(text: "Happy Birthday! May life sprinkle surprises your way.", category: QuoteCategory.birthday),
    Quote(text: "Every birthday is a chance to start fresh. Make it count.", category: QuoteCategory.birthday),
    Quote(text: "Happy Birthday! May your heart be full of gratitude today.", category: QuoteCategory.birthday),
    Quote(text: "Here’s to cake, candles, and cherished memories.", category: QuoteCategory.birthday),
    Quote(text: "Happy Birthday! May you shine brighter each passing year.", category: QuoteCategory.birthday),
    Quote(text: "Birthdays remind us to celebrate life’s gift—YOU.", category: QuoteCategory.birthday),
    Quote(text: "Happy Birthday! May laughter echo through your year ahead.", category: QuoteCategory.birthday),
    Quote(text: "Today is proof you’re a blessing to the world.", category: QuoteCategory.birthday),
    Quote(text: "Happy Birthday! May peace and joy fill your journey ahead.", category: QuoteCategory.birthday),
    Quote(text: "Your birthday is the universe’s way of celebrating you.", category: QuoteCategory.birthday),
    Quote(text: "Happy Birthday! May your dreams soar higher this year.", category: QuoteCategory.birthday),
    Quote(text: "Another candle, another wish—make it magical.", category: QuoteCategory.birthday),
    Quote(text: "Happy Birthday! May happiness follow you like a shadow.", category: QuoteCategory.birthday),
    Quote(text: "Birthdays are tiny festivals of love and joy.", category: QuoteCategory.birthday),
    Quote(text: "Happy Birthday! May today be as special as your smile.", category: QuoteCategory.birthday),
    Quote(text: "Every year is a blessing—celebrate it fully today.", category: QuoteCategory.birthday),
    Quote(text: "Happy Birthday! May you glow inside and out this year.", category: QuoteCategory.birthday),
    Quote(text: "May today mark the start of your brightest year yet.", category: QuoteCategory.birthday),
    Quote(text: "Happy Birthday! Age is proof of living, not limiting.", category: QuoteCategory.birthday),
    Quote(text: "Enjoy cake, cherish moments, and dance into your new year.", category: QuoteCategory.birthday),
    Quote(text: "Happy Birthday! May love and joy be your greatest gifts.", category: QuoteCategory.birthday),
    Quote(text: "Today is your story—make it unforgettable.", category: QuoteCategory.birthday),
    Quote(text: "Happy Birthday! May every candle light your path ahead.", category: QuoteCategory.birthday),
    Quote(text: "Birthdays remind us to smile at the gift of life.", category: QuoteCategory.birthday),
    Quote(text: "Happy Birthday! May the people you love surround you.", category: QuoteCategory.birthday),
    Quote(text: "Today is not just your birthday, it’s everyone’s reason to smile.", category: QuoteCategory.birthday),
    Quote(text: "Happy Birthday! Wishing you endless health and happiness.", category: QuoteCategory.birthday),
    Quote(text: "Let joy fill your soul as you step into a new year.", category: QuoteCategory.birthday),
    Quote(text: "Happy Birthday! May your day sparkle with laughter.", category: QuoteCategory.birthday),
    Quote(text: "Celebrate the gift of you—today and always.", category: QuoteCategory.birthday),
  ];
}

